using UnityEditor;
using System.IO;
using System.Text;
using System.Linq;
using _Project._Common.Scripts.Infrastructure.Configs;
using UnityEngine;

public static class EnumFromSOGenerator
{
    [MenuItem("Tools/Generate Enums From SO")]
    public static void Generate()
    {
        // Находим все EnumDefinitionSO в проекте
        var guids = AssetDatabase.FindAssets("t:EnumDefinitionSO");
        
        foreach (var guid in guids)
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var so = AssetDatabase.LoadAssetAtPath<EnumDefinitionSO>(path);

            if (so == null || string.IsNullOrEmpty(so.EnumName) || so.Values.Length == 0)
                continue;

            GenerateEnum(so.EnumName, so.Values);
        }

        AssetDatabase.Refresh();
        Debug.Log("Enums generated!");
    }

    static void GenerateEnum(string enumName, string[] values)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public enum {enumName}");
        sb.AppendLine("    {");

        for (int i = 0; i < values.Length; i++)
        {
            var value = values[i]
                .Replace(" ", "_")
                .Replace("-", "_")
                .Replace(".", "_");
            
            sb.AppendLine($"        {value} = {i},");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Сохраняем в папку Generated
        var dir = "Assets/_Project/Generated/";
        if (!Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        var filePath = $"{dir}{enumName}.g.cs";
        File.WriteAllText(filePath, sb.ToString());
    }
}